
markdown: kramdown

highlighter: rouge
permalink: pretty
url: https://morvanzhou.github.io
baseurl:

exclude: ['README.md']


# collection and their defaults

collections:
  tutorial_page_contents:
    output: false
  backup:
    output: true
  contents:
    output: true
    permalink: /:path/



defaults:
  - scope:
      path: "_contents/tutorial-home-page"
    values:
      category: description-tutorial-home-page

  - scope:
      path: "_contents/module-descriptions/basic-python"
    values:
      category: description-basic-python

  - scope:
      path: "_contents/module-descriptions/data-manipulation"
    values:
      category: description-data-manipulation

  - scope:
      path: "_contents/module-descriptions/machine-learning"
    values:
      category: description-machine-learning

  - scope:
      path: "_contents/tutorials"
    values:
      editor: Morvan
      author: Morvan
      autoplay: true
      published: true
      comments: true


  - scope:
      path: "_contents/tutorials/machine-learning/ML-intro"
    values:
      layout: tutorial-post
      tut-title: 机器学习-简介系列
      tut-permalink: /tutorials/machine-learning/ML-intro/
      category: ML-intro
      tags: [机器学习, 简介]

  - scope:
      path: "_contents/tutorials/machine-learning/keras"
    values:
      layout: tutorial-post
      tut-title: Keras
      tut-permalink: /tutorials/machine-learning/keras/
      category: keras
      tags: [keras, 神经网络, tensorflow, theano]


  - scope:
      path: "_contents/tutorials/machine-learning/sklearn"
    values:
      layout: tutorial-post
      tut-title: Sklearn
      tut-permalink: /tutorials/machine-learning/sklearn/
      category: sklearn
      tags: [sklearn, scikit-learn, 机器学习]


  - scope:
      path: "_contents/tutorials/machine-learning/tensorflow"
    values:
      layout: tutorial-post
      tut-title: Tensorflow
      tut-permalink: /tutorials/machine-learning/tensorflow/
      category: tensorflow
      tags: [tensorflow, tensorboard, 机器学习, 神经网络]

  - scope:
      path: "_contents/tutorials/machine-learning/theano"
    values:
      layout: tutorial-post
      tut-title: Theano
      tut-permalink: /tutorials/machine-learning/theano/
      category: theano
      tags: [theano, 机器学习, 神经网络]

  - scope:
      path: "_contents/tutorials/data-manipulation/np-pd"
    values:
      layout: tutorial-post
      tut-title: Numpy & Pandas
      tut-permalink: /tutorials/data-manipulation/np-pd/
      category: np-pd
      tags: [numpy, pandas, 数据, 处理]

  - scope:
      path: "_contents/tutorials/data-manipulation/plt"
    values:
      layout: tutorial-post
      tut-title: Matplotlib
      tut-permalink: /tutorials/data-manipulation/plt/
      category: plt
      tags: [matplotlib, plt, 数据可视化]

  - scope:
      path: "_contents/tutorials/python-basic/basic"
    values:
      layout: tutorial-post
      tut-title: Python 基础
      tut-permalink: /tutorials/python-basic/basic/
      category: Python 基础
      tags: [python, 基础]

  - scope:
      path: "_contents/tutorials/python-basic/multiprocessing"
    values:
      layout: tutorial-post
      tut-title: 多进程 Multiprocessing
      tut-permalink: /tutorials/python-basic/multiprocessing/
      category: multiprocessing
      tags: [python, 基础, 多进程, multiprocessing]

  - scope:
      path: "_contents/tutorials/python-basic/threading"
    values:
      layout: tutorial-post
      tut-title: 多线程 Threading
      tut-permalink: /tutorials/python-basic/threading/
      category: threading
      tags: [python, 基础, 多线程, threading]


  - scope:
      path: "_contents/tutorials/python-basic/tkinter"
    values:
      layout: tutorial-post
      tut-title: 窗口 Tkinter
      tut-permalink: /tutorials/python-basic/tkinter/
      category: tkinter
      tags: [python, 基础, GUI, 窗口, tkinter, tk]
